#!/usr/bin/perl

use strict;  # Enforce strict variable declaration
use warnings; # Enable warnings for better debugging
#use MP3::Tag; 

my $temp = '/../include';
my $current_directory = qx(pwd);

# Remove the newline character from the end of the output
chomp($current_directory);
$current_directory=$current_directory.$temp;

# Print the current directory path
print "Current directory: $current_directory\n";

# Specify the spotify_songs of your csv document with the list of songs currently been your favorites' songs on Spotify
my $spotify_songs = $current_directory.'/My Spotify Library.csv';
my @TSRC;
my $TSRC;
my @ISRC;
my $ISRC;
my @spotid;
my $spotid;

my $i = 0;

# Open the file for reading
open(my $fh, '<', $spotify_songs) or die "Could not open file '$spotify_songs' $!";

# Read the file line by line
while (my $line = <$fh>) {
    chomp($line);  # Remove the newline character at the end of the line
    # Split the line based on the specified character (comma in this case)
    my @strings = split(/,/, $line);
    # Print the separated strings
    $ISRC = $strings[5];
    $ISRC[$i]=$ISRC;
    $spotid = $strings[6];
    $spotid[$i]=$spotid;
    $i++;
}
shift @ISRC;
shift @spotid;

print "ISRC(csv): @ISRC\n";
print "spotid(csv): @spotid\n";

# Close the file handle
close($fh);

my @MP3 = `ls ~/Musik/*.mp3 ~/Musik/*.flac ~/Musik/*.wav ~/Musik/*.m4a ~/Musik/*.ogg 2>/dev/null`;
my $size = scalar @MP3;
my @spotifyURL;
my @args;

$args[0]='ffmpeg -y -i ';
$args[1]=' -f ffmetadata metadata.txt -hide_banner';
my $apos = '"';

if($size == 0) {
    print "This folder has no titles from the playlist,
all titles will be downloaded.";
    foreach (@spotid){
        my $hash =$_;
        $hash =~ tr/"//d; #Remove double quotes
        if(!system("spotdl download https://open.spotify.com/intl-de/track/$hash")){
            next;
        }else{ while(system("spotdl download https://open.spotify.com/intl-de/track/$hash")){
            ;
            }
        }
    }
    exit 0;
}else { foreach my $line (@MP3) {
        chomp($line);
        print "Found file: $line\n";
#$args[0]='ffmpeg -y -i ';
#$args[1]=' -f ffmetadata metadata.txt -hide_banner';
#my $apos = '"';
        my $ffmpeg_command =  $args[0].$apos.$line. $apos.$args[1];
        # Capture the output of the ffmpeg command
        print "FFMPEG: $ffmpeg_command\n"; 
        system($ffmpeg_command); #Print song details
        my $file = 'metadata.txt';
        my $search_string = 'TSRC=';
        open(my $fh2, '<', $file) or die "Cannot open file.";
        while (my $line = <$fh2>) {
            if ($line =~ /\b\Q$search_string\E\b\s*(.+)/) {
                push @TSRC, $1;
            }else {
            }
        }
    }
}
print "TSRCs: @TSRC\n\n"; #TSRCs from the files found in the Musik directory
print "ISRC: @ISRC\n\n"; #ISRCs from the songs extracted from the csv file

my %tsrc_lookup = map { $_ => 1 } @TSRC;

#Filter TSRC IDs that are not found in @MP3
my @not_found_isrcs = grep { !$tsrc_lookup{$_} } @ISRC;

# @fltrIDs now contains only ISRCs in @TSRC not present in @MP3

print "Filtered: @not_found_isrcs\n\n"; #The ISRCs that would not have matched any file stored in the Musik directory

my @not_found_spotids;
for (my $i = 0; $i < $#ISRC; $i++) {
    if ($ISRC[$i] = $not_found_isrcs[$i]){
        print "For ISRC[$i] is $spotid[$i]\n";
        push (@not_found_spotids, $spotid);
    }
}
my @failed;
#Download each song by their TSRC
foreach (@not_found_spotids){
    print "Hash is: $_\n";
    # Create a hash for the second array for quick lookup
    my $hash =$_;
    $hash =~ tr/"//d;
    if(!system("spotdl download https://open.spotify.com/track/$hash")){
        next;
    }else{ push (@failed,$hash);
    }
}
