#!/usr/bin/perl

use strict;  # Enforce strict variable declaration
use warnings; # Enable warnings for better debugging

# Print "Hello, World!" to the console
print "Hello, World!\n";
my $temp = '/../include';
my $current_directory = qx(pwd);
# Remove the newline character from the end of the output
chomp($current_directory);
$current_directory=$current_directory.$temp;

# Print the current directory path
print "Current directory: $current_directory\n";
# Specify the spotify_songs of your csv document with the list of songs currently been your favorites' songs on Spotify
my $spotify_songs = $current_directory.'/My Spotify Library.csv';
my @id;
my $id;
my $i = 0;

# Open the file for reading
open(my $fh, '<', $spotify_songs) or die "Could not open file '$spotify_songs' $!";
# Read the file line by line
while (my $line = <$fh>) {
    chomp($line);  # Remove the newline character at the end of the line
    # Split the line based on the specified character (comma in this case)
    my @strings = split(/,/, $line);
    # Print the separated strings
    my $songID = $strings[5];
    # print "songID: $songID\n";
    $id[$i]=$songID;
    $i++;
}

print "ID: @id\n";

# Close the file handle
close($fh);

my @array = `ls 0* /media/aharfuch/E93B-943D/Musik`;
print "ARRAY: @array\n";
my @spotifyURL;
my @TSRC;
my @args;
$args[0]='ffmpeg -y -i ';
$args[1]=' -f ffmetadata metadata.txt -hide_banner';
my $apos = '"';
foreach my $line (@array) {
    chomp($line);
    print "Gefundene Datei: $line\n";
     
    my $ffmpeg_command =  $args[0].$apos.$line. $apos.$args[1];
    # Capture the output of the ffmpeg command
    print "FFMPEG: $ffmpeg_command\n";
    system($ffmpeg_command);
    my $file = 'metadata.txt';
    my $search_string = 'TSRC            : ';
    open(my $fh2, '<', $file) or die "Cannot open file.";
    while (my $line = <$fh2>) {
        if ($line =~ /\b\Q$search_string\E\b\s*(.+)/){
            push @TSRC, $1;
            print "ONE: $1\n";
            exit 0;
            system("rm metadata.txt");
            system("touch metadata.txt");
        }
    }
}

print "TSRC: @TSRC\n";



my $func = 0;
foreach (@TSRC){
   my $hash =$_;
   $hash =~ tr/"//d;
   if(!system("spotdl download $hash")){
       next;
   }else{ my $i=0;
        while(!system("spotdl download $hash")){
            $i++;
            if ($i==25){
                 last;
            }else{ last;
            }
        }
    }
}
