#!/usr/bin/perl

use strict;  # Enforce strict variable declaration
use warnings; # Enable warnings for better debugging
use Scalar::Util 'reftype';

my $temp = '/../include';
my $current_directory = qx(pwd);

# Remove the newline character from the end of the output
chomp($current_directory);
$current_directory=$current_directory.$temp;

# Print the current directory path
print "Current directory: $current_directory\n";

# Specify the spotify_songs of your csv document with the list of songs currently been your favorites' songs on Spotify
my $spotify_songs = $current_directory.'/My Spotify Library.csv';
my @TSRC;
my $TSRC;
my @songID;
my $songID;

my $i = 0;

# Open the file for reading
open(my $fh, '<', $spotify_songs) or die "Could not open file '$spotify_songs' $!";

# Read the file line by line
while (my $line = <$fh>) {
    chomp($line);  # Remove the newline character at the end of the line
    # Split the line based on the specified character (comma in this case)
    my @strings = split(/,/, $line);
    # Print the separated strings
    $songID = $strings[5];
    # print "songID: $songID\n";
    $songID[$i]=$songID;
    $i++;
}

print "IDs: @songID\n";
<STDIN>;
# Close the file handle
close($fh);

my @array = `ls ~/Musik`;
my $size = scalar @array;
my @spotifyURL;
my @args;

$args[0]='ffmpeg -y -i ';
$args[1]=' -f ffmetadata metadata.txt -hide_banner';
my $apos = '"';

if($size == 0) {
    print "This folder has no titles from the playlist,
all titles will be downloaded.";
    foreach (@TSRC){
        my $hash =$_;
        $hash =~ tr/"//d; #Remove double quotes
        if(!system("spotdl download $hash")){
            next;
        }else{ while(system("spotdl download $hash")){
            ;
            }
        }
    }
}else { foreach my $line (@array) {
        chomp($line);
        print "Gefundene Datei: $line\n";
        my $ffmpeg_command =  $args[0].$apos.$line. $apos.$args[1];
        # Capture the output of the ffmpeg command
        print "FFMPEG: $ffmpeg_command\n";
        system($ffmpeg_command);
        my $file = 'metadata.txt';
        my $search_string = 'TSRC=';
        open(my $fh2, '<', $file) or die "Cannot open file.";
        while (my $line = <$fh2>) {
            if ($line =~ /\b\Q$search_string\E\b\s*(.+)/) {
                push @TSRC, $1;
            }else {
            }
        }
    }
}
print "TSRCs: $TSRC[1]\n\n";
print "songID: $songID[1]\n\n";
<STDIN>;

my %local = map { $_ => 1 } @songID;

#Filter TSRC IDs that are not found in @array
my @fltrIDs = grep { not $local{$_} } @TSRC;

# @fltrIDs now contains only songIDs in @TSRC not present in @array

print "Filtered: @fltrIDs\n\n";
print "TSRCs: @songID\n\n";
<STDIN>;

#Download each song by their TSRC
foreach (@TSRC){
    print "Hash is: $_\n";
    # Create a hash for the second array for quick lookup
    my $hash =$_;
    $hash =~ tr/"//d;
    if(!system("spotdl download $hash")){
        next;
    }else{ my $i=0;
        while(!system("spotdl download $hash")){
            $i++;
        }
    }
}
